# Generated by Django 4.2.5 on 2023-09-27 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
