# Generated by Django 4.2.7 on 2023-11-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_discount',
            field=models.BooleanField(default=False),
        ),
    ]
